CREATE TABLE poetic_devices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    act VARCHAR(10),
    scene VARCHAR(10),
    device_name VARCHAR(100),
    device_description TEXT
);

INSERT INTO poetic_devices (act, scene, device_name, device_description) VALUES
('Act 1', 'Scene 1', 'Chiasmus', 'This is a rhetorical device where two or more clauses are balanced against each other by the reversal of their structures. An example is the famous line, "Fair is foul, and foul is fair".'),
('Act 1', 'Scene 1', 'Antithesis', 'This device contrasts two opposing ideas in a balanced manner. For instance, "When the battle’s lost, and won".'),
('Act 1', 'Scene 1', 'Rhyming Couplets', 'The witches speak in rhyming couplets, which gives their speech a rhythmic, spell-like quality. For example, "When shall we three meet again / In thunder, lightning, or in rain?".'),
('Act 1', 'Scene 1', 'Imagery', 'The scene is rich with imagery related to chaos and the supernatural, such as thunder, lightning, and fog. This imagery sets the tone for the dark events that follow.'),
('Act 1', 'Scene 5', 'Metaphor', 'Lady Macbeth uses metaphors to convey her thoughts and intentions. For instance, she asks to be filled "from the crown to the toe top-full of direst cruelty", comparing her body to a vessel that can be filled with evil.'),
('Act 1', 'Scene 5', 'Personification', 'Lady Macbeth personifies night and darkness when she calls on them to hide her deeds: "Come, thick night, / And pall thee in the dunnest smoke of hell". This gives a vivid image of darkness as a concealing force.'),
('Act 1', 'Scene 5', 'Apostrophe', 'She directly addresses abstract concepts like spirits and night, which is a form of apostrophe. For example, "Come, you spirits / That tend on mortal thoughts, unsex me here".'),
('Act 1', 'Scene 5', 'Irony', 'There is dramatic irony in Lady Macbeth\'s advice to Macbeth to "look like the innocent flower, / But be the serpent under\'t". The audience knows their true intentions, while other characters do not.'),
('Act 1', 'Scene 5', 'Imagery', 'Vivid imagery is used throughout the scene, particularly in Lady Macbeth\'s soliloquy. Her descriptions of darkness and cruelty create a powerful visual and emotional impact.'),
('Act 1', 'Scene 5', 'Allusion', 'The reference to the "serpent" under the flower alludes to the biblical story of the Garden of Eden, symbolizing deceit and evil.'),
('Act 1', 'Scene 5', 'Foreshadowing', 'Lady Macbeth\'s invocation of darkness and her plans for Duncan foreshadow the tragic events that will unfold.'),
('Act 1', 'Scene 6', 'Dramatic Irony', 'King Duncan comments on the pleasant atmosphere of Macbeth’s castle, unaware of the impending betrayal and murder. This contrast between appearance and reality heightens the tension.'),
('Act 1', 'Scene 6', 'Imagery', 'The scene is rich with olfactory imagery, as Duncan and Banquo remark on the sweet air around the castle. This imagery creates a false sense of security and peace.'),
('Act 1', 'Scene 6', 'Metaphor', 'The castle is metaphorically described as a welcoming and serene place, which starkly contrasts with the dark intentions harbored within.'),
('Act 1', 'Scene 6', 'Irony', 'Lady Macbeth’s warm and hospitable greeting to Duncan is laced with irony, as she is plotting his murder.'),
('Act 1', 'Scene 7', 'Soliloquy', 'Macbeth’s soliloquy at the beginning of the scene reveals his inner turmoil and moral hesitation about murdering Duncan. This device allows the audience to understand his thoughts and fears intimately.'),
('Act 1', 'Scene 7', 'Metaphor', 'Macbeth uses metaphors to describe his ambition and the consequences of his actions. For example, he compares his ambition to a horse that “o’erleaps itself” and falls on the other side.'),
('Act 1', 'Scene 7', 'Imagery', 'The scene is rich with imagery, particularly in Macbeth’s soliloquy. He uses vivid images of blood and darkness to convey the horror and guilt associated with the murder.'),
('Act 1', 'Scene 7', 'Irony', 'There is dramatic irony in Lady Macbeth’s manipulation of Macbeth. She questions his manhood and resolve, unaware of the deep moral conflict he is experiencing.'),
('Act 1', 'Scene 7', 'Alliteration', 'Shakespeare uses alliteration to emphasize certain points and create a rhythmic flow. For example, Macbeth’s line “If it were done when \'tis done, then \'twere well it were done quickly” uses repeated ‘w’ sounds.'),
('Act 1', 'Scene 7', 'Personification', 'Macbeth personifies his ambition and the consequences of his actions, giving them human qualities and making his internal struggle more relatable.'),
('Act 2', 'Scene 1', 'Imagery', 'Is this a dagger which I see before me, / The handle toward my hand?'),
('Act 2', 'Scene 1', 'Soliloquy', 'Macbeth\'s soliloquy ("Is this a dagger which I see before me...") is a prominent feature in this scene. It reveals his internal struggle and descent into madness as he contemplates the murder of Duncan.'),
('Act 2', 'Scene 1', 'Personification', 'Nature seems dead, and wicked dreams abuse / The curtained sleep'),
('Act 2', 'Scene 1', 'Alliteration', 'Wicked dreams abuse'),
('Act 2', 'Scene 1', 'Metaphor', 'The night is as the day'),
('Act 2', 'Scene 2', 'Onomatopoeia', 'Knock, knock! Who\'s there?'),
('Act 2', 'Scene 2', 'Irony', 'I could not say \'Amen\' / When they did say \'God bless us.\''),
('Act 2', 'Scene 2', 'Symbolism', 'Sleep no more! Macbeth does murder sleep.'),
('Act 2', 'Scene 2', 'Hyperbole', 'Will all great Neptune\'s ocean wash this blood / Clean from my hand?'),
('Act 2', 'Scene 2', 'Repetition', 'Sleep no more!'),
('Act 2', 'Scene 3', 'Comic Relief', 'The scene with the Porter provides comic relief after the intense murder scene. His drunken ramblings contrast sharply with the dark events that have just occurred.'),
('Act 2', 'Scene 3', 'Irony', 'The Porter\'s reference to being the gatekeeper of hell is dramatic irony, as the audience knows that Macbeth\'s castle has just become a site of murder and treachery.'),
('Act 2', 'Scene 3', 'Foreshadowing', 'Here\'s a farmer that hanged himself on the expectation of plenty.'),
('Act 2', 'Scene 3', 'Allusion', 'The Porter alludes to biblical concepts of hell, further emphasizing the theme of damnation.'),
('Act 2', 'Scene 3', 'Pun', 'The Porter’s jokes, like "I\'ll devil-porter it no further," use puns to add a humorous tone, despite the underlying darkness of the situation.'),
('Act 2', 'Scene 4', 'Symbolism', 'By the clock \'tis day, / And yet dark night strangles the traveling lamp.'),
('Act 2', 'Scene 4', 'Personification', 'Dark night strangles the traveling lamp.'),
('Act 2', 'Scene 4', 'Metaphor', 'A falcon, towering in her pride of place, / Was by a mousing owl hawked at and killed.'),
('Act 2', 'Scene 4', 'Foreshadowing', 'The unnatural events described by Ross and the Old Man foreshadow the chaos and disorder that will follow Macbeth’s ascent to the throne.'),
('Act 2', 'Scene 4', 'Simile', 'Like the deed that\'s done.'),
('Act 3', 'Scene 1', 'Foreshadowing', 'To be thus is nothing, but to be safely thus.'),
('Act 3', 'Scene 1', 'Irony', 'Macbeth plans to kill Banquo to prevent the prophecy, but it only deepens his paranoia.'),
('Act 3', 'Scene 1', 'Metaphor', 'Upon my head they placed a fruitless crown, And put a barren scepter in my gripe.'),
('Act 3', 'Scene 1', 'Allusion', 'The reference to the "weird sisters" and their prophecy about Banquo''s descendants.'),
('Act 3', 'Scene 2', 'Personification', 'Better be with the dead, Whom we, to gain our peace, have sent to peace, Than on the torture of the mind to lie.'),
('Act 3', 'Scene 2', 'Imagery', 'Macbeth speaks of his mind being “full of scorpions,” symbolizing his mental anguish.'),
('Act 3', 'Scene 2', 'Metaphor', 'O, full of scorpions is my mind, dear wife!'),
('Act 3', 'Scene 2', 'Dramatic Irony', 'Macbeth''s belief that killing Banquo will secure his safety, though the audience knows it will not.'),
('Act 3', 'Scene 3', 'Symbolism', 'The scene is set at night, symbolizing the evil and treachery of Banquo’s murder.'),
('Act 3', 'Scene 3', 'Foreshadowing', 'The escape of Fleance hints that Macbeth’s efforts to control his fate will ultimately fail.'),
('Act 3', 'Scene 3', 'Alliteration', 'Fly, good Fleance, fly, fly, fly!'),
('Act 3', 'Scene 3', 'Irony', 'The murderers achieve part of their mission, but the escape of Fleance renders their success incomplete.'),
('Act 3', 'Scene 4', 'Imagery', 'Macbeth’s reaction to seeing the ghost emphasizes the stark contrast between his outward appearance of calm and his internal chaos.'),
('Act 3', 'Scene 4', 'Symbolism', 'The ghost’s presence underscores the idea that Macbeth cannot escape the repercussions of his actions.'),
('Act 3', 'Scene 4', 'Irony', 'Macbeth’s public facade of control contrasts with his private fear and hallucinations.'),
('Act 3', 'Scene 4', 'Dramatic Irony', 'The guests’ confusion at Macbeth’s behavior enhances the dramatic irony.'),
('Act 3', 'Scene 5', 'Foreshadowing', 'Hecate’s manipulation of Macbeth’s perceptions foreshadows the illusory nature of his sense of security.'),
('Act 3', 'Scene 5', 'Symbolism', 'Hecate’s presence symbolizes the theme of control exerted by supernatural elements over human actions.'),
('Act 3', 'Scene 5', 'Irony', 'Macbeth’s false sense of security is contrasted with Hecate’s true intentions.'),
('Act 3', 'Scene 5', 'Imagery', 'Hecate’s manipulation through illusions creates a vivid picture of the deceptive nature of her schemes.'),
('Act 3', 'Scene 6', 'Irony', 'The lords’ skepticism about Macbeth’s rule highlights the gap between appearance and reality.'),
('Act 3', 'Scene 6', 'Foreshadowing', 'The discussion about the growing opposition hints at the forthcoming conflict and Macbeth’s downfall.'),
('Act 3', 'Scene 6', 'Symbolism', 'The lords’ suspicions reflect the broader theme of resistance against tyrannical rule.'),
('Act 3', 'Scene 6', 'Imagery', 'The discussion about the state of Scotland paints a grim picture of the consequences of Macbeth’s ambition.'),
('Act 4', 'Scene 1', 'Foreshadowing', 'The apparitions’ prophecies hint at future events and Macbeth’s eventual downfall. Example: The prophecy that Birnam Wood will come to Dunsinane foreshadows the army’s approach to Macbeth’s castle.'),
('Act 4', 'Scene 1', 'Symbolism', 'The apparitions symbolize different aspects of Macbeth’s fears and ambitions. Example: The bloody child represents the idea that Macbeth is invulnerable, while the crowned child with a tree signifies the eventual downfall.'),
('Act 4', 'Scene 1', 'Irony', 'There is dramatic irony in Macbeth’s belief that the prophecies make him invincible, while the audience knows that they are misleading. Example: Macbeth’s confidence is built on the witches’ ambiguous promises, which ultimately contribute to his downfall.'),
('Act 4', 'Scene 1', 'Imagery', 'The apparitions create vivid images that symbolize Macbeth’s psychological state and future events. Example: The vision of Banquo’s line of kings emphasizes Macbeth’s growing paranoia and fear of losing power.'),
('Act 4', 'Scene 2', 'Irony', 'Lady Macduff’s frustration with Macduff’s departure contrasts with the tragic fate that befalls her and her son. Example: Lady Macduff complains about her husband’s actions, unaware of the impending danger.'),
('Act 4', 'Scene 2', 'Imagery', 'The scene uses imagery of violence and betrayal to convey the tragedy of Lady Macduff’s fate. Example: The murder of Lady Macduff and her son is depicted with stark, brutal imagery.'),
('Act 4', 'Scene 2', 'Symbolism', 'Lady Macduff and her son symbolize the innocence and suffering caused by Macbeth’s ambition. Example: Their deaths represent the innocent lives affected by political corruption.'),
('Act 4', 'Scene 2', 'Dialogue', 'The conversation between Lady Macduff and Ross highlights her vulnerability and frustration. Example: Lady Macduff’s dialogue expresses her concerns and sense of betrayal.'),
('Act 4', 'Scene 3', 'Irony', 'Malcolm’s pretense of being a worse tyrant than Macbeth is ironic, as it reveals the lengths to which he goes to test Macduff’s loyalty. Example: Malcolm’s false claims serve to highlight Macduff’s true commitment to justice.'),
('Act 4', 'Scene 3', 'Symbolism', 'Malcolm’s test symbolizes the struggle between good and evil and the quest for a legitimate ruler. Example: Malcolm’s test represents the search for a true leader who can restore order.'),
('Act 4', 'Scene 3', 'Imagery', 'The scene uses vivid imagery to convey the emotional impact of the news about Macduff’s family. Example: Ross’s news is depicted with stark and sorrowful imagery.'),
('Act 4', 'Scene 3', 'Dialogue', 'The dialogue between Malcolm and Macduff reveals their characters and the nature of their alliance. Example: Malcolm’s test and Macduff’s response illustrate their respective values and motivations.'),
('Act 5', 'Scene 1', 'Imagery', 'Lady Macbeth’s obsessive hand-washing creates a vivid image of her psychological torment and guilt.'),
('Act 5', 'Scene 2', 'Foreshadowing', 'The gathering of nobles foreshadows their united effort against Macbeth’s tyranny.'),
('Act 5', 'Scene 3', 'Irony', 'Macbeth’s belief in his invincibility is ironic, as the witches’ prophecies lead to his downfall.'),
('Act 5', 'Scene 4', 'Symbolism', 'The branches from Birnam Wood symbolize the impending doom for Macbeth, fulfilling the witches’ prophecy.'),
('Act 5', 'Scene 5', 'Soliloquy', 'Macbeth’s soliloquy reflects his disillusionment and the futility of life, emphasizing the theme of existential despair.'),
('Act 5', 'Scene 6', 'Symbolism', 'The battle itself symbolizes the clash between good and evil, with Malcolm representing rightful leadership.'),
('Act 5', 'Scene 7', 'Dramatic Irony', 'Macbeth’s confidence in his invincibility contrasts with the audience’s awareness of his impending doom.');
