CREATE TABLE important_questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    act VARCHAR(10),
    scene VARCHAR(10),
    question_text TEXT
);

INSERT INTO important_questions (act, scene, question_text) VALUES
('Act 1', 'Scene 1', 'How does the opening scene set the tone for the rest of the play?'),
('Act 1', 'Scene 2', 'What are the implications of Macbeth being named Thane of Cawdor and later King?'),
('Act 1', 'Scene 3', 'How do the witches’ prophecies influence Macbeth’s actions and thoughts?'),
('Act 1', 'Scene 4', 'What is the significance of Duncan’s decision to name Malcolm as his heir?'),
('Act 1', 'Scene 5', 'What does Lady Macbeth’s reaction to Macbeth’s letter reveal about her character?'),
('Act 1', 'Scene 5', 'How does Lady Macbeth plan to influence Macbeth to fulfill the witches’ prophecy?'),
('Act 1', 'Scene 5', 'What does Lady Macbeth mean when she asks the spirits to “unsex” her?'),
('Act 1', 'Scene 5', 'Why does Lady Macbeth believe Macbeth is too full of “the milk of human kindness”?'),
('Act 1', 'Scene 5', 'What is the significance of Lady Macbeth’s soliloquy in this scene?'),
('Act 1', 'Scene 5', 'How does Lady Macbeth’s ambition compare to Macbeth’s at this point in the play?'),
('Act 1', 'Scene 5', 'What does Lady Macbeth mean when she tells Macbeth to “look like the innocent flower, but be the serpent under’t”?'),
('Act 1', 'Scene 5', 'How does the news of King Duncan’s visit change Lady Macbeth’s plans?'),
('Act 1', 'Scene 5', 'What role does gender play in Lady Macbeth’s manipulation of Macbeth?'),
('Act 1', 'Scene 5', 'How does this scene set the stage for the events that follow in the play?'),
('Act 1', 'Scene 6', 'What is the significance of Duncan\'s comments about the castle\'s pleasant atmosphere?'),
('Act 1', 'Scene 6', 'How does Lady Macbeth\'s behavior in this scene contrast with her earlier actions and words?'),
('Act 1', 'Scene 6', 'What role does dramatic irony play in this scene?'),
('Act 1', 'Scene 6', 'Why is the presence of the martlet (a bird) mentioned, and what does it symbolize?'),
('Act 1', 'Scene 6', 'How does Shakespeare use imagery to enhance the scene\'s atmosphere?'),
('Act 1', 'Scene 6', 'What does Duncan\'s trust in Macbeth and Lady Macbeth reveal about his character?'),
('Act 1', 'Scene 6', 'How does this scene foreshadow the events to come?'),
('Act 1', 'Scene 6', 'What is the significance of the formal greetings exchanged between Duncan and Lady Macbeth?'),
('Act 1', 'Scene 6', 'How does the setting of Inverness contribute to the overall mood of the play?'),
('Act 1', 'Scene 6', 'What themes are highlighted in this scene, and how do they relate to the play\'s broader themes?'),
('Act 1', 'Scene 7', 'What reasons does Macbeth give for not wanting to kill Duncan?'),
('Act 1', 'Scene 7', 'How does Macbeth describe his ambition in this scene?'),
('Act 1', 'Scene 7', 'What arguments does Lady Macbeth use to persuade Macbeth to commit the murder?'),
('Act 1', 'Scene 7', 'How does Lady Macbeth challenge Macbeth\'s manhood?'),
('Act 1', 'Scene 7', 'What plan does Lady Macbeth propose to murder Duncan?'),
('Act 1', 'Scene 7', 'How does Macbeth react to Lady Macbeth\'s plan initially?'),
('Act 1', 'Scene 7', 'What does Macbeth mean by "bloody instructions, which, being taught, return to plague the inventor"?'),
('Act 1', 'Scene 7', 'How does the imagery in Macbeth\'s soliloquy reflect his internal conflict?'),
('Act 1', 'Scene 7', 'What does Lady Macbeth say she would do to keep a promise, and how does this affect Macbeth?'),
('Act 1', 'Scene 7', 'What is the significance of Macbeth\'s final decision at the end of the scene?'),
('Act 2', 'Scene 1', 'Why does Macbeth see a dagger before him, and what does it symbolize?'),
('Act 2', 'Scene 1', 'How does Macbeth\'s soliloquy reveal his inner conflict about killing King Duncan?'),
('Act 2', 'Scene 1', 'What is the significance of the time (midnight) in this scene?'),
('Act 2', 'Scene 1', 'How does the imagery of darkness contribute to the atmosphere of the scene?'),
('Act 2', 'Scene 1', 'What role does Banquo play in this scene, and how does his attitude toward the witches contrast with Macbeth’s?'),
('Act 2', 'Scene 1', 'Why does Macbeth lie to Banquo about his thoughts on the witches’ prophecy?'),
('Act 2', 'Scene 1', 'What does Macbeth mean when he says, “Nature seems dead, and wicked dreams abuse / The curtained sleep”?'),
('Act 2', 'Scene 1', 'How does Shakespeare use personification in Macbeth’s soliloquy, and what effect does it have?'),
('Act 2', 'Scene 1', 'What does the bell tolling signify, and why does Macbeth react to it as he does?'),
('Act 2', 'Scene 1', 'How does this scene set the stage for the events that follow in Act 2?'),
('Act 2', 'Scene 2', 'What is the significance of Lady Macbeth’s comment, “That which hath made them drunk hath made me bold”?'),
('Act 2', 'Scene 2', 'How does Lady Macbeth’s reaction to the murder contrast with Macbeth’s reaction?'),
('Act 2', 'Scene 2', 'Why is Macbeth unable to say “Amen” after killing Duncan, and what does this inability suggest about his state of mind?'),
('Act 2', 'Scene 2', 'What does Macbeth mean when he says, “Methought I heard a voice cry, ‘Sleep no more! / Macbeth does murder sleep’”?'),
('Act 2', 'Scene 2', 'How does the motif of blood in this scene reflect Macbeth’s guilt?'),
('Act 2', 'Scene 2', 'Why does Lady Macbeth take charge after the murder, and how does this reflect the power dynamics in their relationship?'),
('Act 2', 'Scene 2', 'What is the significance of Macbeth’s line, “Will all great Neptune’s ocean wash this blood / Clean from my hand?”'),
('Act 2', 'Scene 2', 'How does Lady Macbeth’s response to Macbeth’s guilt differ from her own feelings later in the play?'),
('Act 2', 'Scene 2', 'Why is the knocking at the gate so significant, and how does it heighten the tension in this scene?'),
('Act 2', 'Scene 2', 'How does this scene explore the theme of guilt and its consequences?'),
('Act 2', 'Scene 3', 'How does the Porter’s scene function as comic relief in the play, and why is it placed here?'),
('Act 2', 'Scene 3', 'What is the significance of the Porter’s comparison of Macbeth’s castle to hell?'),
('Act 2', 'Scene 3', 'How do the reactions of Macduff and Lennox to Duncan’s murder contrast with Macbeth’s?'),
('Act 2', 'Scene 3', 'What does Macbeth’s killing of the guards suggest about his state of mind and his attempts to cover his tracks?'),
('Act 2', 'Scene 3', 'How does Lady Macbeth’s fainting contribute to the dramatic tension of the scene?'),
('Act 2', 'Scene 3', 'What is the importance of Macduff’s refusal to tell Lady Macbeth about Duncan’s murder directly?'),
('Act 2', 'Scene 3', 'How does this scene advance the theme of appearance versus reality?'),
('Act 2', 'Scene 3', 'Why does Macbeth claim that his actions (killing the guards) were motivated by love for Duncan?'),
('Act 2', 'Scene 3', 'How does this scene set up the suspicion that begins to fall on Macbeth?'),
('Act 2', 'Scene 3', 'What is the significance of Malcolm and Donalbain deciding to flee Scotland, and how does this decision impact the play’s plot?'),
('Act 2', 'Scene 4', 'What is the significance of the unnatural events described by Ross and the Old Man in this scene?'),
('Act 2', 'Scene 4', 'How do these unnatural occurrences reflect the themes of disorder and the disruption of natural order?'),
('Act 2', 'Scene 4', 'What is the symbolic meaning of the falcon being killed by a mousing owl, and how does it relate to the play’s events?'),
('Act 2', 'Scene 4', 'How does this scene help to establish the atmosphere of unease and chaos in Scotland following Duncan’s murder?'),
('Act 2', 'Scene 4', 'What does Ross mean when he says, “By the clock ’tis day, / And yet dark night strangles the traveling lamp”?'),
('Act 2', 'Scene 4', 'How does the conversation between Ross and the Old Man provide commentary on the state of Scotland under Macbeth’s rule?'),
('Act 2', 'Scene 4', 'What is the significance of Macduff’s decision not to attend Macbeth’s coronation?'),
('Act 2', 'Scene 4', 'How does Ross’s reaction to Duncan’s death differ from Macduff’s, and what does this suggest about their characters?'),
('Act 2', 'Scene 4', 'How does this scene foreshadow the conflicts that will arise later in the play?'),
('Act 2', 'Scene 4', 'What does this scene reveal about the impact of Macbeth’s actions on the natural and social order in Scotland?'),
('Act 3', 'Scene 1', 'What are Banquo's suspicions regarding Macbeth, and how does this affect Macbeth’s plans?'),
('Act 3', 'Scene 1', 'How does Macbeth’s ambition drive him to plot Banquo’s murder?'),
('Act 3', 'Scene 1', 'What role do the witches play in influencing Macbeth’s actions?'),
('Act 3', 'Scene 2', 'How does Lady Macbeth respond to Macbeth’s growing paranoia?'),
('Act 3', 'Scene 2', 'What does Macbeth mean when he says, "We have scorched the snake, not killed it"?'),
('Act 3', 'Scene 2', 'In what ways does Macbeth’s character change in this scene?'),
('Act 3', 'Scene 3', 'What is significant about Fleance’s escape from the murderers?'),
('Act 3', 'Scene 3', 'How does the murder of Banquo impact Macbeth’s state of mind?'),
('Act 3', 'Scene 4', 'What does the appearance of Banquo’s ghost signify about Macbeth’s guilt?'),
('Act 3', 'Scene 4', 'How does Lady Macbeth attempt to manage the situation at the banquet?'),
('Act 3', 'Scene 4', 'What does Macbeth’s behavior at the banquet reveal about his mental state?'),
('Act 3', 'Scene 5', 'What is Hecate’s role in the play, and how does she plan to manipulate Macbeth?'),
('Act 3', 'Scene 5', 'How does Hecate’s influence foreshadow the events that follow?'),
('Act 3', 'Scene 6', 'What are the reactions of Lennox and the lord to Macbeth’s rule?'),
('Act 3', 'Scene 6', 'How does this scene set the stage for the future conflict in the play?'),
('Act 4', 'Scene 1', 'What are the three apparitions that Macbeth sees, and what do they predict?'),
('Act 4', 'Scene 1', 'How does Macbeth react to the apparitions’ prophecies?'),
('Act 4', 'Scene 1', 'What does the vision of Banquo’s descendants reveal about Macbeth’s fears?'),
('Act 4', 'Scene 1', 'How do the prophecies affect Macbeth’s sense of security and actions?'),
('Act 4', 'Scene 1', 'What is the significance of the prophecy that Birnam Wood will come to Dunsinane?'),
('Act 4', 'Scene 1', 'How does Macbeth’s reaction to the witches’ prophecies reflect his character development?'),
('Act 4', 'Scene 1', 'What role does ambiguity play in the witches’ prophecies?'),
('Act 4', 'Scene 1', 'How does the scene foreshadow the events leading to Macbeth’s downfall?'),
('Act 4', 'Scene 1', 'How does the imagery of the apparitions contribute to the scene’s atmosphere?'),
('Act 4', 'Scene 1', 'What impact does the scene have on Macbeth’s relationship with the witches?'),
('Act 4', 'Scene 2', 'What are Lady Macduff’s feelings about Macduff’s departure, and how does she express them?'),
('Act 4', 'Scene 2', 'How does the murder of Lady Macduff and her son reflect the theme of political corruption?'),
('Act 4', 'Scene 2', 'What is the significance of Lady Macduff’s conversation with Ross?'),
('Act 4', 'Scene 2', 'How does the scene illustrate the personal costs of Macbeth’s ambition?'),
('Act 4', 'Scene 2', 'What role does Lady Macduff’s character play in the play’s exploration of innocence and suffering?'),
('Act 4', 'Scene 2', 'How does the imagery in this scene contribute to its emotional impact?'),
('Act 4', 'Scene 2', 'What does the senseless violence against Lady Macduff and her son reveal about Macbeth’s rule?'),
('Act 4', 'Scene 2', 'How does the scene contrast with the political machinations of Macbeth?'),
('Act 4', 'Scene 2', 'What are the consequences of Lady Macduff’s death for the overall plot?'),
('Act 4', 'Scene 2', 'How does this scene enhance the play’s exploration of themes related to tyranny and its effects?'),
('Act 4', 'Scene 3', 'Why does Malcolm test Macduff’s loyalty, and how does he do it?'),
('Act 4', 'Scene 3', 'How does Macduff prove his integrity in response to Malcolm’s test?'),
('Act 4', 'Scene 3', 'What is Malcolm’s true intention, and how does it affect his alliance with Macduff?'),
('Act 4', 'Scene 3', 'How does Macduff react to the news of his family’s murder?'),
('Act 4', 'Scene 3', 'What role does this scene play in the development of the final conflict in the play?'),
('Act 4', 'Scene 3', 'How does Malcolm’s character contrast with Macbeth’s?'),
('Act 4', 'Scene 3', 'What themes related to kingship and tyranny are explored in this scene?'),
('Act 4', 'Scene 3', 'How does the dialogue between Malcolm and Macduff reveal their motivations?'),
('Act 4', 'Scene 3', 'What impact does this scene have on Macduff’s character arc?'),
('Act 4', 'Scene 3', 'How does the emotional weight of the scene contribute to the play’s tragic elements?'),
('Act 5', 'Scene 1', 'How does Lady Macbeth’s behavior in this scene reflect her psychological state?'),
('Act 5', 'Scene 1', 'What does Lady Macbeth’s obsessive hand-washing symbolize?'),
('Act 5', 'Scene 2', 'What are the Scottish nobles discussing in this scene?'),
('Act 5', 'Scene 2', 'How does the scene reflect the growing opposition to Macbeth’s rule?'),
('Act 5', 'Scene 3', 'How does Macbeth react to the news of Lady Macbeth’s death?'),
('Act 5', 'Scene 3', 'What does Macbeth’s confidence reveal about his character development?'),
('Act 5', 'Scene 4', 'What strategy does Malcolm use to approach Dunsinane?'),
('Act 5', 'Scene 4', 'How does this scene foreshadow the outcome of the battle?'),
('Act 5', 'Scene 5', 'What themes are reflected in Macbeth’s soliloquy after Lady Macbeth’s death?'),
('Act 5', 'Scene 5', 'How does Macbeth’s despair contribute to the play’s tragic elements?'),
('Act 5', 'Scene 6', 'What significance does the battle have in the overall plot?'),
('Act 5', 'Scene 6', 'How does this scene illustrate the contrast between Macbeth and Malcolm?'),
('Act 5', 'Scene 7', 'How does the confrontation between Macbeth and Macduff resolve the play’s conflict?'),
('Act 5', 'Scene 7', 'What does Macbeth’s realization about Macduff reveal about the consequences of his ambition?');
